services:
  - name: yabin
    type: web
    runtime: image
    image:
      url: docker.io/yureien/yabin:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "3000"
databases:
  - name: db-db
    plan: free
